---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  selector:
    name: kafka

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka
          image: debezium/kafka
          env:
          - name: BROKER_ID
            value: "1"
          - name: ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: HOST_NAME
            value: 127.0.0.1
          - name: CREATE_TOPICS
            value: topic1:2:1,topic2:1:2
            # WORKAROUND - Todo: Search or open issue: 
            # org.apache.kafka.common.config.ConfigException: Invalid value tcp://10.51.241.56:9092 for configuration port: Not a number of type INT
          - name: KAFKA_PORT
            value: "9092"
